djangoProject1/WebNovels/urls.py
from django.urls import include, path
from .views import SignUpView


from . import views
app_name = 'WebNovels'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('form', views.CreateNovel.as_view(), name='Form'),
    path('form2', views.CreateAuthor.as_view(), name='Form2'),
    path('form3', views.CreateTag.as_view(), name='Form3'),
    path('<id>', views.detail_view, name='detail'),
    path('<id>/update', views.update_view, name='update'),
    path('<id>/delete', views.delete_view, name='delete'),
    path("signup/", SignUpView.as_view(), name="signup"),

]

djangoProject1/djangoProject1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='WebNovels/homeAuth.html'), name='home2'),
    path('webnovels/', include('WebNovels.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('mwakamoon/', admin.site.urls),
    path('form/', include('WebNovels.urls'))

]

djangoProject1/WebNovels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Tag(models.Model):
    name = models.CharField(max_length=200, default='Tag')

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=200, default='Author')
    date = models.DateTimeField(auto_now_add=True)
    mail = models.EmailField(null=True)

    def __str__(self):
        return self.name


class WebNovels(models.Model):

    STATUS = (
        ('Completed', 'Completed'),
        ('On a Break', 'On a Break'),
        ('Ongoing', 'Ongoing'),
    )

    name = models.CharField(max_length=200, default='Webnovel')
    pub_date = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True)
    views = models.IntegerField(null=True)
    price = models.IntegerField(null=True)
    length = models.IntegerField(null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    tags = models.ManyToManyField(Tag, blank=True, default='Tag')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

djangoProject1/WebNovels/views.py
from django.forms import ModelForm
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class NovelFrom(ModelForm):
    class Meta:
        model = WebNovels
        fields = ['name', 'price', 'author', 'status', 'length', 'tags', 'views']

class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'mail']
class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

class CreateNovel(generic.CreateView):
    form_class = NovelFrom
    model = WebNovels
    template_name = 'WebNovels/form.html'
    success_url = '/webnovels/'
    def form_valid(self, form):
        novel = form.save(commit=False)
        novel.user = self.request.user
        novel.save()
        return super().form_valid(form)

class CreateAuthor(generic.CreateView):
    form_class = AuthorForm
    model = AuthorForm
    template_name = 'WebNovels/form2.html'
    success_url = '/webnovels/form'
    def form_valid(self, form):
        author = form.save(commit=False)
        author.user = self.request.user
        author.save()
        return super().form_valid(form)

class CreateTag(generic.CreateView):
    form_class = TagForm
    model = TagForm
    template_name = 'WebNovels/form3.html'
    success_url = '/webnovels/form'
    def form_valid(self, form):
        tag = form.save(commit=False) # Don't save the tag yet.
        tag.user = self.request.user # Set the user of the tag to the current user
        tag.save()
        return super().form_valid(form) # Call the "real" save() method.


def detail_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # add the dictionary during initialization
    context["data"] = WebNovels.objects.get(id=id)

    return render(request, "WebNovels/detail_view.html", context)


def update_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(WebNovels, id=id)

    # pass the object as instance in form
    form = NovelFrom(request.POST or None, instance=obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/webnovels/" + id)

    # add form dictionary to context
    context["form"] = form
    return render(request, "WebNovels/update_detail.html", context)


def delete_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(WebNovels, id=id)

    if request.method == "POST":
        # delete object
        obj.delete()
        # after deleting redirect to
        # home page
        return HttpResponseRedirect("/webnovels/")

    return render(request, "WebNovels/delete_view.html", context)


class Index(generic.ListView):
    model = WebNovels
    template_name = 'WebNovels/home.html'
    context_object_name = "books"

    def get_queryset(self):
        return WebNovels.objects.all()

class SignUpView(generic.CreateView):
    form_class = UserCreationForm # This is the form that will be used to create a new user
    success_url = reverse_lazy("login") # This is the URL that the user will be redirected to after a successful signup
    template_name = "registration/signup.html" # This is the template that will be used to display the signup form

djangoProject1/WebNovels/templates/WebNovels/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/delete_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Page</title>
    <link rel="stylesheet" href="css/custom.css">
</head>
<body>
    <div class="main">
        <!-- Create a Form -->
        <form method="POST">
            <!-- Security token by Django -->
            {% csrf_token %}
            Are you want to delete this item ?
            <br>
            <input type="submit" value="Yes" /> <br>
            <a href="/">Cancel </a>
        </form>
    </div>
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail View</title>
        <style>
        body {
	font-family: Arial, sans-serif;
	margin: 0;
	padding: 0;
	background-color: #f0f0f0;
	}
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            font-size: 2.5rem;
            margin-top: 0;
            text-align: center;
            color: #333;
        }
        h2 {
            font-size: 1.5rem;
            margin-top: 20px;
            margin-bottom: 10px;
            color: #333;
        }
        ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }
        li {
            margin-bottom: 5px;
        }
        li span {
            font-weight: bold;
        }
        .button {
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            }

        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
            }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
            }

    </style>
</head>
<body class="container">
    <button onclick="window.location.href='http://127.0.0.1:8000/webnovels/';"class="button button1">Home</button>
    <li><span>Title:</span> {{ data.name }}</li>
    <li><span>Author:</span> {{ data.author }}</li>
    <li><span>Price:</span> ${{ data.price }}</li>
    <li><span>Status:</span> {{ data.status}}</li>
    <li><span>Publication Date:</span> {{ data.pub_date}}</li>
    <li><span>Views:</span> {{ data.views}}</li>
    <li><span>Length:</span> {{ data.length}}</li>
    <li><span>Genre:</span> {% for genre in data.tags.all %} {{ genre }}</li>
    <li><span>Published by:</span> {{ data.user }}</li>
    {% endfor %}
    <br>
    <button onclick="window.location.href= '{% url 'WebNovels:delete' data.id %}'" class="button button1">Delete</button>
    <button onclick="window.location.href= '{% url 'WebNovels:update' data.id %}'" class="button button1">Update</button>
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WebNovel Form</title>
</head>
<body>
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <button onclick="window.location.href='http://127.0.0.1:8000/webnovels/form3';">Add Tag</button>
    <button onclick="window.location.href='http://127.0.0.1:8000/webnovels/form2';">Add Author</button>
{% endblock %}

</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/form2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Form</title>
</head>
<body>
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/form3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tag Form</title>
</head>
<body>
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>My Book Retail App</title>
    <style>
	body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f0f0f0;
    }
.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    background-color: #fff;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}
h1 {
    font-size: 2.5rem;
    margin-top: 0;
    text-align: center;
    color: #333;
}
h2 {
    font-size: 1.5rem;
    margin-top: 20px;
    margin-bottom: 10px;
    color: #333;
}
ul {
    list-style: none;
    margin: 0;
    padding: 0;
}
li {
    margin-bottom: 5px;
}
li span {
    font-weight: bold;
}
.no-books {
    color: #777;
}
.button {
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    transition-duration: 0.4s;
    cursor: pointer;
    }

.button1 {
    background-color: white;
    color: black;
    border: 2px solid #4CAF50;
    }

.button1:hover {
    background-color: #4CAF50;
    color: white;
    }

.aligned {
    text-align: center;
            }
    </style>
</head>
<body>
	<div class="container">
		<h1>Welcome to My WebNovel Retail App</h1>
		<button class="button button1"><a href="{% url 'home2' %}">Account</a></button>

		{% if books %}
			<h2>Available Books:</h2>
			<ul>
				{% for book in books %}
					<li><span>Title:</span> {{ book.name }}</li>
					<li><span>Author:</span> {{ book.author }}</li>
					<li><span>Price:</span> ${{ book.price }}</li>
					<li><span>Status:</span> {{ book.status}}</li>
                    <li><span>Publication Date:</span> {{ book.pub_date}}</li>
                    <li><span>Views:</span> {{ book.views}}</li>
                    <li><span>Length:</span> {{ book.length}}</li>
                    <li><span>Genre:</span> <br>{% for genre in book.tags.all %}{{ genre }}</li>
                    {% endfor %}
                    <li><span>Published by:</span> {{ book.user }}</li>
                    <br>
                    <button onclick="window.location.href= '{% url 'WebNovels:detail' book.id %}'" class="button button1">Details</button>
					<hr>
				{% endfor %}
			</ul>
		{% else %}
			<p class="no-books">No books available at the moment.</p>
		{% endif %}
	</div>
    <div class="aligned">
        <button onclick="window.location.href='http://127.0.0.1:8000/webnovels/form';"class="button button1">Add WebNovel</button>
    </div>
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/homeAuth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Auth</title>
</head>
<body>
    {% extends 'WebNovels/base.html' %}

    {% block title %}Home{% endblock %}

    {% block content %}
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
        <br>
        <a href="{% url 'WebNovels:signup' %}">Sign Up</a>
    {% endif %}
        <br>
        <a href="{% url 'WebNovels:index' %}">Home</a>
        <br>
        <p><a href="{% url 'password_reset' %}">Reset Password</a></p>
    {% endblock %}
</body>
</html>

djangoProject1/WebNovels/templates/WebNovels/update_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Page</title>
    <link rel="stylesheet" href="css/custom.css">
</head>
<body>
<div class="main">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</div>
</body>
</html>